name: secure_student_management
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  bloc: ^9.2.1
  flutter_bloc: ^9.1.1
  cupertino_icons: ^1.0.8
  dio: ^5.0.0
  flutter_secure_storage: ^9.0.0
  jwt_decoder: ^2.0.1
  flutter_native_splash: ^2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

# إعدادات أيقونة التطبيق (App Launcher Icon)
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/assets/icons/log.png"
  adaptive_icon_background: "#0047BA"
  adaptive_icon_foreground: "lib/assets/icons/log.png"

# إعدادات شاشة البداية (Splash Screen)
flutter_native_splash:
  color: "#0047BA"
  image: lib/assets/icons/log.png
  android_12:
    color: "#0047BA"
    image: lib/assets/icons/log.png
    icon_background_color: "#0047BA"

flutter:
  uses-material-design: true
  assets:
    - lib/assets/icons/log.png